// frontend/components/StockTable.vue
<template>
  <div class="stock-table-container">
    <!-- Table wrapper for horizontal scroll on mobile -->
    <div class="overflow-x-auto">
      <table class="stock-table">
        <thead>
          <tr>
            <th @click="sortBy('ticker')" class="sortable">
              Ticker
              <span v-if="sortColumn === 'ticker'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('name')" class="sortable">
              Name
              <span v-if="sortColumn === 'name'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('price')" class="sortable">
              Price
              <span v-if="sortColumn === 'price'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('dcf')" class="sortable">
              DCF
              <span v-if="sortColumn === 'dcf'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('ddm')" class="sortable">
              DDM
              <span v-if="sortColumn === 'ddm'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('pe')" class="sortable">
              P/E
              <span v-if="sortColumn === 'pe'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('graham')" class="sortable">
              Graham
              <span v-if="sortColumn === 'graham'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="sortBy('status')" class="sortable">
              Status
              <span v-if="sortColumn === 'status'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th v-if="showActions">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="stock in sortedStocks" :key="stock.ticker">
            <td class="ticker-cell">
              <NuxtLink :to="`/stocks/${stock.ticker}`" class="ticker-link">
                {{ stock.ticker }}
              </NuxtLink>
            </td>
            <td class="name-cell">{{ stock.name }}</td>
            <td class="price-cell">{{ formatCurrency(stock.price) }}</td>
            <td class="fair-value-cell">{{ formatCurrency(stock.dcf) }}</td>
            <td class="fair-value-cell">{{ formatValue(stock.ddm) }}</td>
            <td class="fair-value-cell">{{ formatCurrency(stock.pe) }}</td>
            <td class="fair-value-cell">{{ formatValue(stock.graham) }}</td>
            <td class="status-cell">
              <span :class="['status-badge', getStatusClass(stock.status)]">
                {{ formatStatus(stock.status) }}
              </span>
            </td>
            <td v-if="showActions" class="actions-cell">
              <slot name="actions" :stock="stock"></slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div v-if="showPagination && totalPages > 1" class="pagination">
      <button
        @click="goToPage(currentPage - 1)"
        :disabled="currentPage === 1"
        class="pagination-btn"
      >
        Previous
      </button>
      <span class="pagination-info">
        Page {{ currentPage }} of {{ totalPages }}
      </span>
      <button
        @click="goToPage(currentPage + 1)"
        :disabled="currentPage === totalPages"
        class="pagination-btn"
      >
        Next
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

export interface StockTableRow {
  ticker: string;
  name: string;
  price: number;
  dcf: number;
  ddm: number | null;
  pe: number;
  graham: number | null;
  status: 'undervalued' | 'fairly_priced' | 'overvalued';
}

interface Props {
  stocks: StockTableRow[];
  showActions?: boolean;
  itemsPerPage?: number;
  showPagination?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showActions: false,
  itemsPerPage: 10,
  showPagination: true,
});

// Sorting state
const sortColumn = ref<keyof StockTableRow>('ticker');
const sortDirection = ref<'asc' | 'desc'>('asc');

// Pagination state
const currentPage = ref(1);

// Computed: sorted stocks
const sortedStocks = computed(() => {
  const sorted = [...props.stocks].sort((a, b) => {
    const aVal = a[sortColumn.value];
    const bVal = b[sortColumn.value];

    // Handle null values
    if (aVal === null && bVal === null) return 0;
    if (aVal === null) return 1;
    if (bVal === null) return -1;

    // Compare values
    if (typeof aVal === 'string' && typeof bVal === 'string') {
      return sortDirection.value === 'asc'
        ? aVal.localeCompare(bVal)
        : bVal.localeCompare(aVal);
    }

    if (typeof aVal === 'number' && typeof bVal === 'number') {
      return sortDirection.value === 'asc' ? aVal - bVal : bVal - aVal;
    }

    return 0;
  });

  // Apply pagination
  if (props.showPagination) {
    const start = (currentPage.value - 1) * props.itemsPerPage;
    const end = start + props.itemsPerPage;
    return sorted.slice(start, end);
  }

  return sorted;
});

// Computed: total pages
const totalPages = computed(() => {
  return Math.ceil(props.stocks.length / props.itemsPerPage);
});

// Methods
const sortBy = (column: keyof StockTableRow) => {
  if (sortColumn.value === column) {
    sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc';
  } else {
    sortColumn.value = column;
    sortDirection.value = 'asc';
  }
  currentPage.value = 1; // Reset to first page on sort
};

const goToPage = (page: number) => {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page;
  }
};

const formatCurrency = (value: number | null): string => {
  if (value === null) return 'N/A';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
};

const formatValue = (value: number | null): string => {
  if (value === null) return 'N/A';
  return formatCurrency(value);
};

const formatStatus = (status: string): string => {
  const statusMap: Record<string, string> = {
    undervalued: 'Undervalued',
    fairly_priced: 'Fair',
    overvalued: 'Overvalued',
  };
  return statusMap[status] || status;
};

const getStatusClass = (status: string): string => {
  const classMap: Record<string, string> = {
    undervalued: 'status-undervalued',
    fairly_priced: 'status-fair',
    overvalued: 'status-overvalued',
  };
  return classMap[status] || '';
};
</script>

<style scoped>
.stock-table-container {
  width: 100%;
  margin: 1rem 0;
}

.overflow-x-auto {
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

.stock-table {
  width: 100%;
  border-collapse: collapse;
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.stock-table thead {
  background: #f9fafb;
  border-bottom: 2px solid #e5e7eb;
}

.stock-table th {
  padding: 0.75rem 1rem;
  text-align: left;
  font-weight: 600;
  font-size: 0.875rem;
  color: #374151;
  white-space: nowrap;
}

.stock-table th.sortable {
  cursor: pointer;
  user-select: none;
  transition: background-color 0.2s;
}

.stock-table th.sortable:hover {
  background: #f3f4f6;
}

.sort-indicator {
  margin-left: 0.25rem;
  font-size: 0.75rem;
}

.stock-table td {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #e5e7eb;
  font-size: 0.875rem;
  color: #1f2937;
}

.stock-table tbody tr:hover {
  background: #f9fafb;
}

.ticker-cell {
  font-weight: 600;
}

.ticker-link {
  color: #2563eb;
  text-decoration: none;
  transition: color 0.2s;
}

.ticker-link:hover {
  color: #1d4ed8;
  text-decoration: underline;
}

.name-cell {
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.price-cell,
.fair-value-cell {
  font-family: 'Courier New', monospace;
  text-align: right;
}

.status-cell {
  text-align: center;
}

.status-badge {
  display: inline-block;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
}

.status-undervalued {
  background: #d1fae5;
  color: #065f46;
}

.status-fair {
  background: #f3f4f6;
  color: #374151;
}

.status-overvalued {
  background: #fee2e2;
  color: #991b1b;
}

.actions-cell {
  text-align: center;
}

/* Pagination */
.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  margin-top: 1rem;
  padding: 1rem;
}

.pagination-btn {
  padding: 0.5rem 1rem;
  background: #2563eb;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.pagination-btn:hover:not(:disabled) {
  background: #1d4ed8;
}

.pagination-btn:disabled {
  background: #9ca3af;
  cursor: not-allowed;
}

.pagination-info {
  font-size: 0.875rem;
  color: #6b7280;
}

/* Mobile responsive */
@media (max-width: 768px) {
  .stock-table th,
  .stock-table td {
    padding: 0.5rem;
    font-size: 0.75rem;
  }

  .name-cell {
    max-width: 120px;
  }

  .pagination {
    flex-direction: column;
    gap: 0.5rem;
  }

  .pagination-btn {
    width: 100%;
  }
}

@media (max-width: 640px) {
  .stock-table th,
  .stock-table td {
    padding: 0.375rem;
    font-size: 0.7rem;
  }

  .status-badge {
    padding: 0.125rem 0.5rem;
    font-size: 0.625rem;
  }
}
</style>

// frontend/components/StockTable.tsx
'use client';

import { useMemo } from 'react';
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  flexRender,
  ColumnDef,
  SortingState,
} from '@tanstack/react-table';
import { useState } from 'react';
import { ChevronUpIcon, ChevronDownIcon } from '@heroicons/react/24/outline';
import type { FairValueResult } from '@/types';

interface StockTableProps {
  data: FairValueResult[];
  onRemove?: (ticker: string) => void;
  showRemoveButton?: boolean;
  className?: string;
}

/**
 * StockTable component displays stock comparison data with sortable columns
 * Requirements: 4.2, 4.3
 */
export default function StockTable({
  data,
  onRemove,
  showRemoveButton = false,
  className = '',
}: StockTableProps) {
  const [sorting, setSorting] = useState<SortingState>([]);

  // Format currency
  const formatCurrency = (value: number | null): string => {
    if (value === null) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(value);
  };

  // Get valuation status badge
  const getStatusBadge = (status: 'undervalued' | 'fairly_priced' | 'overvalued') => {
    const statusConfig = {
      undervalued: {
        text: 'Undervalued',
        classes: 'bg-green-50 text-green-700 border-green-200',
        dotClasses: 'bg-green-500',
      },
      fairly_priced: {
        text: 'Fair',
        classes: 'bg-white text-gray-700 border-gray-200',
        dotClasses: 'bg-gray-400',
      },
      overvalued: {
        text: 'Overvalued',
        classes: 'bg-red-50 text-red-700 border-red-200',
        dotClasses: 'bg-red-500',
      },
    };

    const config = statusConfig[status];

    return (
      <span
        className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium border ${config.classes}`}
      >
        <span className={`w-1.5 h-1.5 rounded-full mr-1.5 ${config.dotClasses}`}></span>
        {config.text}
      </span>
    );
  };

  // Define columns
  const columns = useMemo<ColumnDef<FairValueResult>[]>(
    () => [
      {
        accessorKey: 'ticker',
        header: 'Ticker',
        cell: (info) => (
          <div className="font-semibold text-black">{info.getValue() as string}</div>
        ),
      },
      {
        accessorKey: 'currentPrice',
        header: 'Current Price',
        cell: (info) => (
          <div className="text-gray-900">{formatCurrency(info.getValue() as number)}</div>
        ),
      },
      {
        id: 'dcfFairValue',
        accessorFn: (row) => row.dcf.fairValue,
        header: 'DCF',
        cell: (info) => (
          <div className="text-gray-900">{formatCurrency(info.getValue() as number)}</div>
        ),
      },
      {
        id: 'ddmFairValue',
        accessorFn: (row) => row.ddm.fairValue,
        header: 'DDM',
        cell: (info) => (
          <div className="text-gray-900">{formatCurrency(info.getValue() as number | null)}</div>
        ),
      },
      {
        id: 'peFairValue',
        accessorFn: (row) => row.relativeValue.peRatioFairValue,
        header: 'P/E',
        cell: (info) => (
          <div className="text-gray-900">{formatCurrency(info.getValue() as number)}</div>
        ),
      },
      {
        id: 'grahamFairValue',
        accessorFn: (row) => row.graham.fairValue,
        header: 'Graham',
        cell: (info) => (
          <div className="text-gray-900">{formatCurrency(info.getValue() as number | null)}</div>
        ),
      },
      {
        accessorKey: 'valuationStatus',
        header: 'Status',
        cell: (info) => getStatusBadge(info.getValue() as any),
      },
      ...(showRemoveButton
        ? [
            {
              id: 'actions',
              header: '',
              cell: (info: any) => (
                <button
                  onClick={() => onRemove?.(info.row.original.ticker)}
                  className="text-red-600 hover:text-red-800 text-sm font-medium transition-colors"
                  aria-label={`Remove ${info.row.original.ticker}`}
                >
                  Remove
                </button>
              ),
            } as ColumnDef<FairValueResult>,
          ]
        : []),
    ],
    [showRemoveButton, onRemove]
  );

  // Create table instance
  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
    },
    onSortingChange: setSorting,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    initialState: {
      pagination: {
        pageSize: 10,
      },
    },
  });

  if (data.length === 0) {
    return (
      <div className="text-center py-12 bg-white border border-gray-200 rounded-lg">
        <p className="text-gray-500">No stocks to display</p>
      </div>
    );
  }

  return (
    <div className={`bg-white border border-gray-200 rounded-lg overflow-hidden ${className}`}>
      {/* Table - Responsive with horizontal scroll on mobile */}
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <th
                    key={header.id}
                    className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {header.isPlaceholder ? null : (
                      <div
                        className={
                          header.column.getCanSort()
                            ? 'flex items-center gap-2 cursor-pointer select-none hover:text-gray-700'
                            : ''
                        }
                        onClick={header.column.getToggleSortingHandler()}
                      >
                        {flexRender(header.column.columnDef.header, header.getContext())}
                        {header.column.getCanSort() && (
                          <span className="flex flex-col">
                            {header.column.getIsSorted() === 'asc' ? (
                              <ChevronUpIcon className="w-4 h-4" />
                            ) : header.column.getIsSorted() === 'desc' ? (
                              <ChevronDownIcon className="w-4 h-4" />
                            ) : (
                              <div className="flex flex-col">
                                <ChevronUpIcon className="w-3 h-3 text-gray-300" />
                                <ChevronDownIcon className="w-3 h-3 text-gray-300 -mt-1" />
                              </div>
                            )}
                          </span>
                        )}
                      </div>
                    )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {table.getRowModel().rows.map((row) => (
              <tr key={row.id} className="hover:bg-gray-50 transition-colors">
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id} className="px-4 py-4 whitespace-nowrap text-sm">
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {table.getPageCount() > 1 && (
        <div className="px-4 py-3 bg-gray-50 border-t border-gray-200 sm:px-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <button
                onClick={() => table.previousPage()}
                disabled={!table.getCanPreviousPage()}
                className="px-3 py-1 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Previous
              </button>
              <button
                onClick={() => table.nextPage()}
                disabled={!table.getCanNextPage()}
                className="px-3 py-1 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Next
              </button>
            </div>
            <div className="text-sm text-gray-700">
              Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
