// frontend/app/[locale]/stocks/[ticker]/details/page.tsx
'use client';

import { use } from 'react';
import Link from 'next/link';
import { useModelDetails } from '@/hooks/useStockData';
import { ArrowLeftIcon, LockClosedIcon } from '@heroicons/react/24/outline';

interface ModelDetailsPageProps {
  params: Promise<{ ticker: string }>;
}

/**
 * Model details page showing detailed calculation steps (Pro only)
 * Requirements: 3.1, 3.2, 3.3, 3.4, 3.5
 */
export default function ModelDetailsPage({ params }: ModelDetailsPageProps) {
  const { ticker } = use(params);
  const tickerUpper = ticker.toUpperCase();

  // TODO: Get user subscription status from auth store
  const isPro = false; // This should come from auth store

  // Fetch model details
  const {
    data: modelDetails,
    isLoading,
    error,
  } = useModelDetails(tickerUpper);

  // Show upgrade prompt for free users (Requirements: 3.1)
  if (!isPro) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="container mx-auto px-4 py-8">
          <Link
            href={`/stocks/${tickerUpper}`}
            className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6 transition-colors"
          >
            <ArrowLeftIcon className="w-5 h-5 mr-2" />
            Back to Stock Detail
          </Link>

          <div className="max-w-2xl mx-auto">
            <div className="bg-white rounded-lg shadow-lg p-8 text-center">
              <div className="w-16 h-16 bg-yellow-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <LockClosedIcon className="w-8 h-8 text-yellow-600" />
              </div>
              
              <h1 className="text-3xl font-bold text-gray-900 mb-4">
                Pro Feature
              </h1>
              
              <p className="text-lg text-gray-600 mb-8">
                Detailed model breakdowns with calculation steps, assumptions, and projected cash flows are available for Pro subscribers.
              </p>

              <div className="bg-gray-50 rounded-lg p-6 mb-8">
                <h3 className="font-semibold text-gray-900 mb-4">What you'll get with Pro:</h3>
                <ul className="text-left space-y-3 text-gray-700">
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-green-500 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Complete DCF calculation with 10-year projections</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-green-500 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Detailed assumptions and methodology</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-green-500 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Historical financial data analysis</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-green-500 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Sensitivity analysis and scenarios</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-green-500 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Plus batch comparison, alerts, and exports</span>
                  </li>
                </ul>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  href="/pricing"
                  className="px-8 py-3 bg-gray-900 text-white font-semibold rounded-lg hover:bg-gray-800 transition-colors"
                >
                  Upgrade to Pro
                </Link>
                <Link
                  href={`/stocks/${tickerUpper}`}
                  className="px-8 py-3 bg-white text-gray-900 border border-gray-300 font-semibold rounded-lg hover:bg-gray-50 transition-colors"
                >
                  Back to Stock
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="container mx-auto px-4 py-8">
          <div className="animate-pulse">
            <div className="h-8 bg-gray-200 rounded w-1/4 mb-4"></div>
            <div className="h-64 bg-gray-200 rounded mb-4"></div>
            <div className="h-64 bg-gray-200 rounded"></div>
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="container mx-auto px-4 py-8">
          <Link
            href={`/stocks/${tickerUpper}`}
            className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6"
          >
            <ArrowLeftIcon className="w-5 h-5 mr-2" />
            Back to Stock Detail
          </Link>
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
            <h2 className="text-xl font-semibold text-red-800 mb-2">Error Loading Model Details</h2>
            <p className="text-red-600">{error.message || 'Failed to load model details'}</p>
          </div>
        </div>
      </div>
    );
  }

  // No data state
  if (!modelDetails) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="container mx-auto px-4 py-8">
          <Link
            href={`/stocks/${tickerUpper}`}
            className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6"
          >
            <ArrowLeftIcon className="w-5 h-5 mr-2" />
            Back to Stock Detail
          </Link>
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center">
            <h2 className="text-xl font-semibold text-yellow-800 mb-2">No Data Available</h2>
            <p className="text-yellow-600">Model details not found for {tickerUpper}</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        {/* Back Button */}
        <Link
          href={`/stocks/${tickerUpper}`}
          className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6 transition-colors"
        >
          <ArrowLeftIcon className="w-5 h-5 mr-2" />
          Back to Stock Detail
        </Link>

        {/* Page Header */}
        <div className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">
            Detailed Model Breakdown
          </h1>
          <p className="text-lg text-gray-600">{tickerUpper}</p>
        </div>

        {/* DCF Model Details (Requirements: 3.2, 3.3, 3.4) */}
        {modelDetails.dcf && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">DCF Model</h2>
            
            {/* Assumptions (Requirements: 3.3) */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Key Assumptions</h3>
              <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {Object.entries(modelDetails.dcf.assumptions || {}).map(([key, value]) => (
                  <div key={key} className="bg-gray-50 rounded-lg p-4">
                    <div className="text-sm text-gray-600 mb-1">
                      {key.replace(/([A-Z])/g, ' $1').trim()}
                    </div>
                    <div className="text-lg font-semibold text-gray-900">
                      {typeof value === 'number' && key.toLowerCase().includes('rate')
                        ? `${(value * 100).toFixed(2)}%`
                        : String(value)}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Projected Cash Flows (Requirements: 3.4, 3.5) */}
            {modelDetails.dcf.projectedCashFlows && (
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-4">
                  Projected Cash Flows (10 Years)
                </h3>
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Year
                        </th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Projected FCF
                        </th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Discount Factor
                        </th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Present Value
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {modelDetails.dcf.projectedCashFlows.map((cf: any, index: number) => (
                        <tr key={index} className="hover:bg-gray-50">
                          <td className="px-4 py-3 whitespace-nowrap text-sm font-medium text-gray-900">
                            Year {index + 1}
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-900 text-right">
                            ${(cf.cashFlow / 1e6).toFixed(2)}M
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-900 text-right">
                            {cf.discountFactor?.toFixed(4) || 'N/A'}
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-900 text-right">
                            ${(cf.presentValue / 1e6).toFixed(2)}M
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Calculation Summary */}
            {modelDetails.dcf.summary && (
              <div className="mt-6 pt-6 border-t border-gray-200">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Calculation Summary</h3>
                <div className="space-y-2 text-sm">
                  {Object.entries(modelDetails.dcf.summary).map(([key, value]) => (
                    <div key={key} className="flex justify-between">
                      <span className="text-gray-600">
                        {key.replace(/([A-Z])/g, ' $1').trim()}:
                      </span>
                      <span className="font-semibold text-gray-900">
                        {typeof value === 'number' ? `$${value.toFixed(2)}` : String(value)}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Other Model Details */}
        {modelDetails.ddm && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Dividend Discount Model
            </h2>
            <p className="text-gray-600">
              Detailed DDM calculations and assumptions...
            </p>
          </div>
        )}

        {/* Methodology */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <h3 className="text-lg font-semibold text-blue-900 mb-2">Methodology Note</h3>
          <p className="text-blue-800 text-sm">
            All calculations are based on publicly available financial data and industry-standard valuation methodologies. 
            Past performance does not guarantee future results. This analysis is for informational purposes only and 
            should not be considered investment advice.
          </p>
        </div>
      </div>
    </div>
  );
}

// frontend/pages/stocks/[ticker]/details.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Navigation -->
    <nav class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex items-center">
            <NuxtLink to="/" class="text-2xl font-bold text-black">
              Stockmeter
            </NuxtLink>
          </div>
          <div class="flex items-center space-x-4">
            <template v-if="isAuthenticated">
              <NuxtLink
                to="/watchlist"
                class="text-gray-700 hover:text-black px-3 py-2 rounded-md text-sm font-medium"
              >
                Watchlist
              </NuxtLink>
              <NuxtLink
                to="/compare"
                class="text-gray-700 hover:text-black px-3 py-2 rounded-md text-sm font-medium"
              >
                Compare
              </NuxtLink>
              <span class="text-gray-700">{{ user?.name }}</span>
              <span v-if="isPro" class="px-2 py-1 text-xs font-semibold text-white bg-black rounded">
                PRO
              </span>
              <button
                @click="handleLogout"
                class="text-gray-700 hover:text-black px-3 py-2 rounded-md text-sm font-medium"
              >
                Logout
              </button>
            </template>
            <template v-else>
              <NuxtLink
                to="/login"
                class="text-gray-700 hover:text-black px-3 py-2 rounded-md text-sm font-medium"
              >
                Login
              </NuxtLink>
              <NuxtLink
                to="/register"
                class="bg-black text-white hover:bg-gray-800 px-4 py-2 rounded-md text-sm font-medium"
              >
                Sign Up
              </NuxtLink>
            </template>
          </div>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Back Button -->
      <NuxtLink
        :to="`/stocks/${ticker}`"
        class="flex items-center text-gray-600 hover:text-black mb-6 transition-colors"
      >
        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
        Back to {{ ticker }}
      </NuxtLink>

      <!-- Upgrade Prompt for Free Users -->
      <div v-if="!isPro && isAuthenticated" class="bg-white rounded-lg shadow-sm p-8 text-center">
        <div class="max-w-2xl mx-auto">
          <div class="w-16 h-16 bg-black rounded-full mx-auto mb-4 flex items-center justify-center">
            <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          </div>
          <h2 class="text-3xl font-bold text-black mb-4">Pro Feature</h2>
          <p class="text-lg text-gray-600 mb-8">
            Detailed model breakdowns with calculation steps, assumptions, and projected cash flows are available exclusively for Pro subscribers.
          </p>
          <div class="space-y-4 mb-8">
            <div class="flex items-start text-left">
              <svg class="w-6 h-6 text-green-500 mr-3 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
              <div>
                <div class="font-semibold text-black">Complete Calculation Steps</div>
                <div class="text-gray-600">See exactly how each fair value is calculated</div>
              </div>
            </div>
            <div class="flex items-start text-left">
              <svg class="w-6 h-6 text-green-500 mr-3 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
              <div>
                <div class="font-semibold text-black">10-Year Projections</div>
                <div class="text-gray-600">View detailed revenue and cash flow forecasts</div>
              </div>
            </div>
            <div class="flex items-start text-left">
              <svg class="w-6 h-6 text-green-500 mr-3 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
              <div>
                <div class="font-semibold text-black">All Model Assumptions</div>
                <div class="text-gray-600">Understand the inputs behind each valuation</div>
              </div>
            </div>
          </div>
          <NuxtLink
            to="/pricing"
            class="inline-block bg-black text-white px-8 py-3 rounded-lg text-lg font-medium hover:bg-gray-800 transition-colors"
          >
            Upgrade to Pro
          </NuxtLink>
        </div>
      </div>

      <!-- Login Prompt for Non-Authenticated Users -->
      <div v-else-if="!isAuthenticated" class="bg-white rounded-lg shadow-sm p-8 text-center">
        <h2 class="text-3xl font-bold text-black mb-4">Sign In Required</h2>
        <p class="text-lg text-gray-600 mb-8">
          Please sign in to access detailed model breakdowns.
        </p>
        <div class="space-x-4">
          <NuxtLink
            to="/login"
            class="inline-block bg-black text-white px-8 py-3 rounded-lg text-lg font-medium hover:bg-gray-800 transition-colors"
          >
            Sign In
          </NuxtLink>
          <NuxtLink
            to="/register"
            class="inline-block bg-white text-black border-2 border-black px-8 py-3 rounded-lg text-lg font-medium hover:bg-gray-50 transition-colors"
          >
            Create Account
          </NuxtLink>
        </div>
      </div>

      <!-- Model Details Content (Pro Users Only) -->
      <div v-else>
        <!-- Loading State -->
        <div v-if="modelDetailsLoading" class="flex justify-center items-center py-20">
          <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-black"></div>
        </div>

        <!-- Error State -->
        <div v-else-if="modelDetailsError" class="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
          <p class="text-red-700">{{ modelDetailsError }}</p>
          <button
            @click="loadModelDetails"
            class="mt-4 bg-black text-white px-6 py-2 rounded-lg hover:bg-gray-800 transition-colors"
          >
            Try Again
          </button>
        </div>

        <!-- Model Details -->
        <div v-else-if="modelDetails">
          <h1 class="text-3xl font-bold text-black mb-8">
            Detailed Valuation Breakdown for {{ ticker }}
          </h1>

          <!-- DCF Model Details -->
          <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <h2 class="text-2xl font-bold text-black mb-4">Discounted Cash Flow (DCF)</h2>
            
            <!-- Assumptions -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Key Assumptions</h3>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Revenue Growth Rate</div>
                  <div class="text-xl font-bold text-black">
                    {{ (modelDetails.dcf.assumptions.revenueGrowthRate * 100).toFixed(2) }}%
                  </div>
                </div>
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">WACC (Discount Rate)</div>
                  <div class="text-xl font-bold text-black">
                    {{ (modelDetails.dcf.assumptions.wacc * 100).toFixed(2) }}%
                  </div>
                </div>
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Terminal Growth Rate</div>
                  <div class="text-xl font-bold text-black">
                    {{ (modelDetails.dcf.assumptions.terminalGrowthRate * 100).toFixed(2) }}%
                  </div>
                </div>
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Projection Period</div>
                  <div class="text-xl font-bold text-black">
                    {{ modelDetails.dcf.assumptions.projectionYears }} years
                  </div>
                </div>
              </div>
            </div>

            <!-- Projected Cash Flows -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Projected Free Cash Flows</h3>
              <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Year</th>
                      <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Revenue</th>
                      <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Free Cash Flow</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    <tr v-for="(fcf, index) in modelDetails.dcf.projectedFCF" :key="index">
                      <td class="px-4 py-3 text-sm text-gray-900">Year {{ index + 1 }}</td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">
                        {{ formatCurrency(modelDetails.dcf.projectedRevenue[index] ?? 0) }}
                      </td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">
                        {{ formatCurrency(fcf) }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Calculation Steps -->
            <div>
              <h3 class="text-lg font-semibold text-black mb-3">Calculation Steps</h3>
              <ol class="space-y-2">
                <li v-for="(step, index) in modelDetails.dcf.detailedSteps" :key="index" class="flex">
                  <span class="flex-shrink-0 w-6 h-6 bg-black text-white rounded-full flex items-center justify-center text-xs mr-3">
                    {{ index + 1 }}
                  </span>
                  <span class="text-gray-700">{{ step }}</span>
                </li>
              </ol>
            </div>
          </div>

          <!-- DDM Model Details -->
          <div v-if="modelDetails.ddm.applicable" class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <h2 class="text-2xl font-bold text-black mb-4">Dividend Discount Model (DDM)</h2>
            
            <!-- Assumptions -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Key Assumptions</h3>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Dividend Growth Rate</div>
                  <div class="text-xl font-bold text-black">
                    {{ (modelDetails.ddm.assumptions.dividendGrowthRate * 100).toFixed(2) }}%
                  </div>
                </div>
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Discount Rate</div>
                  <div class="text-xl font-bold text-black">
                    {{ (modelDetails.ddm.assumptions.discountRate * 100).toFixed(2) }}%
                  </div>
                </div>
              </div>
            </div>

            <!-- Historical Dividends -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Historical Dividends</h3>
              <div class="flex space-x-4 overflow-x-auto">
                <div v-for="(dividend, index) in modelDetails.ddm.historicalDividends" :key="index" class="bg-gray-50 p-4 rounded-lg min-w-[120px]">
                  <div class="text-sm text-gray-600">Year {{ index + 1 }}</div>
                  <div class="text-lg font-bold text-black">
                    {{ formatCurrency(dividend) }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Calculation Steps -->
            <div>
              <h3 class="text-lg font-semibold text-black mb-3">Calculation Steps</h3>
              <ol class="space-y-2">
                <li v-for="(step, index) in modelDetails.ddm.detailedSteps" :key="index" class="flex">
                  <span class="flex-shrink-0 w-6 h-6 bg-black text-white rounded-full flex items-center justify-center text-xs mr-3">
                    {{ index + 1 }}
                  </span>
                  <span class="text-gray-700">{{ step }}</span>
                </li>
              </ol>
            </div>
          </div>

          <!-- Relative Valuation Details -->
          <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <h2 class="text-2xl font-bold text-black mb-4">Relative Valuation (Peer Comparison)</h2>
            
            <!-- Peer Comparisons -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Industry Peers</h3>
              <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr>
                      <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Company</th>
                      <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">P/E Ratio</th>
                      <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">P/B Ratio</th>
                      <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">P/S Ratio</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    <tr v-for="peer in modelDetails.relativeValue.peerComparisons" :key="peer.ticker">
                      <td class="px-4 py-3 text-sm">
                        <div class="font-medium text-gray-900">{{ peer.ticker }}</div>
                        <div class="text-gray-500 text-xs">{{ peer.name }}</div>
                      </td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">{{ peer.pe.toFixed(2) }}</td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">{{ peer.pb.toFixed(2) }}</td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">{{ peer.ps.toFixed(2) }}</td>
                    </tr>
                    <tr class="bg-gray-50 font-semibold">
                      <td class="px-4 py-3 text-sm text-gray-900">Industry Median</td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">
                        {{ modelDetails.relativeValue.industryMedians.pe.toFixed(2) }}
                      </td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">
                        {{ modelDetails.relativeValue.industryMedians.pb.toFixed(2) }}
                      </td>
                      <td class="px-4 py-3 text-sm text-gray-900 text-right">
                        {{ modelDetails.relativeValue.industryMedians.ps.toFixed(2) }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Calculation Steps -->
            <div>
              <h3 class="text-lg font-semibold text-black mb-3">Calculation Steps</h3>
              <ol class="space-y-2">
                <li v-for="(step, index) in modelDetails.relativeValue.detailedSteps" :key="index" class="flex">
                  <span class="flex-shrink-0 w-6 h-6 bg-black text-white rounded-full flex items-center justify-center text-xs mr-3">
                    {{ index + 1 }}
                  </span>
                  <span class="text-gray-700">{{ step }}</span>
                </li>
              </ol>
            </div>
          </div>

          <!-- Graham Number Details -->
          <div v-if="modelDetails.graham.applicable" class="bg-white rounded-lg shadow-sm p-6">
            <h2 class="text-2xl font-bold text-black mb-4">Graham Number</h2>
            
            <!-- Assumptions -->
            <div class="mb-6">
              <h3 class="text-lg font-semibold text-black mb-3">Key Inputs</h3>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Earnings Per Share (EPS)</div>
                  <div class="text-xl font-bold text-black">
                    {{ formatCurrency(modelDetails.graham.assumptions.eps) }}
                  </div>
                </div>
                <div class="bg-gray-50 p-4 rounded-lg">
                  <div class="text-sm text-gray-600">Book Value Per Share</div>
                  <div class="text-xl font-bold text-black">
                    {{ formatCurrency(modelDetails.graham.assumptions.bookValuePerShare) }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Calculation Steps -->
            <div>
              <h3 class="text-lg font-semibold text-black mb-3">Calculation Steps</h3>
              <ol class="space-y-2">
                <li v-for="(step, index) in modelDetails.graham.detailedSteps" :key="index" class="flex">
                  <span class="flex-shrink-0 w-6 h-6 bg-black text-white rounded-full flex items-center justify-center text-xs mr-3">
                    {{ index + 1 }}
                  </span>
                  <span class="text-gray-700">{{ step }}</span>
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue';

const route = useRoute();
const { isAuthenticated, isPro, user, logout } = useAuth();
const {
  modelDetails,
  modelDetailsLoading,
  modelDetailsError,
  getModelDetails,
} = useStockData();

const ticker = computed(() => route.params.ticker as string);

// Load model details on mount (only for Pro users)
const loadModelDetails = async () => {
  if (isPro.value) {
    await getModelDetails(ticker.value);
  }
};

onMounted(() => {
  loadModelDetails();
});

// Format currency
const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
};

const handleLogout = async () => {
  await logout();
};
</script>
