// frontend/pages/compare.vue
<template>
  <div class="compare-page">
    <div class="container">
      <h1 class="page-title">Stock Comparison</h1>
      <p class="page-description">
        Compare multiple stocks side-by-side to evaluate investment opportunities
      </p>

      <!-- Add Stock Section -->
      <div class="add-stock-section">
        <div class="search-wrapper">
          <StockSearchBar
            @select="handleStockSelect"
            placeholder="Search and add stocks to compare..."
          />
        </div>
        <div class="stock-limit-info">
          <span v-if="!isPro" class="limit-text">
            Free users: Limited to 1 stock. 
            <NuxtLink to="/pricing" class="upgrade-link">Upgrade to Pro</NuxtLink> 
            to compare up to 50 stocks.
          </span>
          <span v-else class="limit-text">
            {{ selectedTickers.length }} / 50 stocks selected
          </span>
        </div>
      </div>

      <!-- Selected Stocks Pills -->
      <div v-if="selectedTickers.length > 0" class="selected-stocks">
        <div class="stock-pill" v-for="ticker in selectedTickers" :key="ticker">
          <span>{{ ticker }}</span>
          <button @click="removeStock(ticker)" class="remove-btn" aria-label="Remove stock">
            ×
          </button>
        </div>
      </div>

      <!-- Upgrade Prompt for Free Users -->
      <div v-if="!isPro && selectedTickers.length >= 1" class="upgrade-prompt">
        <div class="upgrade-content">
          <h3>Unlock Batch Comparison</h3>
          <p>Upgrade to Pro to compare up to 50 stocks simultaneously and export results.</p>
          <NuxtLink to="/pricing" class="upgrade-btn">
            Upgrade to Pro
          </NuxtLink>
        </div>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="loading-state">
        <div class="spinner"></div>
        <p>Loading comparison data...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="error-state">
        <p class="error-message">{{ error }}</p>
        <button @click="loadComparison" class="retry-btn">Retry</button>
      </div>

      <!-- Comparison Table -->
      <div v-if="!loading && !error && comparisonData.length > 0" class="comparison-section">
        <div class="comparison-header">
          <h2>Comparison Results</h2>
          <button
            v-if="isPro"
            @click="handleExport"
            class="export-btn"
            :disabled="exportLoading"
          >
            {{ exportLoading ? 'Exporting...' : 'Export Results' }}
          </button>
        </div>

        <StockTable
          :stocks="comparisonData"
          :show-actions="true"
          :show-pagination="comparisonData.length > 10"
        >
          <template #actions="{ stock }">
            <button @click="removeStock(stock.ticker)" class="action-remove-btn">
              Remove
            </button>
          </template>
        </StockTable>
      </div>

      <!-- Empty State -->
      <div v-if="!loading && !error && selectedTickers.length === 0" class="empty-state">
        <svg class="empty-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
        </svg>
        <h3>No stocks selected</h3>
        <p>Search and add stocks above to start comparing</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { StockSearchResult, FairValueResult } from '~/types';
import type { StockTableRow } from '~/components/StockTable.vue';

definePageMeta({
  middleware: 'auth',
});

const { isPro } = useAuth();
const config = useRuntimeConfig();
const authStore = useAuthStore();

// State
const selectedTickers = ref<string[]>([]);
const comparisonData = ref<StockTableRow[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const exportLoading = ref(false);

// Methods
const handleStockSelect = (stock: StockSearchResult) => {
  // Check if already selected
  if (selectedTickers.value.includes(stock.ticker)) {
    return;
  }

  // Check tier limitations
  if (!isPro.value && selectedTickers.value.length >= 1) {
    error.value = 'Free users can only compare 1 stock. Upgrade to Pro for batch comparison.';
    return;
  }

  if (isPro.value && selectedTickers.value.length >= 50) {
    error.value = 'Maximum 50 stocks can be compared at once.';
    return;
  }

  // Add ticker
  selectedTickers.value.push(stock.ticker);
  error.value = null;

  // Load comparison data
  loadComparison();
};

const removeStock = (ticker: string) => {
  selectedTickers.value = selectedTickers.value.filter(t => t !== ticker);
  comparisonData.value = comparisonData.value.filter(s => s.ticker !== ticker);
  error.value = null;
};

const loadComparison = async () => {
  if (selectedTickers.value.length === 0) {
    comparisonData.value = [];
    return;
  }

  loading.value = true;
  error.value = null;

  try {
    const headers: Record<string, string> = {};
    if (authStore.accessToken) {
      headers.Authorization = `Bearer ${authStore.accessToken}`;
    }

    const response = await $fetch<{ comparisons: FairValueResult[] }>('/api/stocks/compare', {
      baseURL: config.public.apiBaseUrl,
      method: 'POST',
      headers,
      body: {
        tickers: selectedTickers.value,
      },
    });

    // Transform to table format
    comparisonData.value = response.comparisons.map(result => ({
      ticker: result.ticker,
      name: result.ticker, // API should return name, using ticker as fallback
      price: result.currentPrice,
      dcf: result.dcf.fairValue,
      ddm: result.ddm.fairValue,
      pe: result.relativeValue.peRatioFairValue,
      graham: result.graham.fairValue,
      status: result.valuationStatus,
    }));
  } catch (err: any) {
    console.error('Comparison error:', err);
    error.value = err.data?.error?.message || 'Failed to load comparison data';
    comparisonData.value = [];
  } finally {
    loading.value = false;
  }
};

const handleExport = async () => {
  if (!isPro.value) {
    error.value = 'Export is only available for Pro users';
    return;
  }

  exportLoading.value = true;
  error.value = null;

  try {
    const headers: Record<string, string> = {};
    if (authStore.accessToken) {
      headers.Authorization = `Bearer ${authStore.accessToken}`;
    }

    // Export as CSV
    const blob = await $fetch<Blob>('/api/download', {
      baseURL: config.public.apiBaseUrl,
      method: 'GET',
      headers,
      params: {
        format: 'csv',
        tickers: selectedTickers.value.join(','),
      },
      responseType: 'blob',
    });

    // Create download link
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `stock-comparison-${Date.now()}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  } catch (err: any) {
    console.error('Export error:', err);
    error.value = err.data?.error?.message || 'Failed to export data';
  } finally {
    exportLoading.value = false;
  }
};
</script>

<style scoped>
.compare-page {
  min-height: 100vh;
  background: #f9fafb;
  padding: 2rem 1rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
}

.page-title {
  font-size: 2rem;
  font-weight: 700;
  color: #111827;
  margin-bottom: 0.5rem;
}

.page-description {
  font-size: 1rem;
  color: #6b7280;
  margin-bottom: 2rem;
}

.add-stock-section {
  background: white;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  margin-bottom: 1.5rem;
}

.search-wrapper {
  margin-bottom: 1rem;
}

.stock-limit-info {
  font-size: 0.875rem;
  color: #6b7280;
}

.limit-text {
  display: block;
}

.upgrade-link {
  color: #2563eb;
  text-decoration: none;
  font-weight: 500;
}

.upgrade-link:hover {
  text-decoration: underline;
}

.selected-stocks {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.stock-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  background: #eff6ff;
  color: #1e40af;
  border-radius: 9999px;
  font-size: 0.875rem;
  font-weight: 500;
}

.remove-btn {
  background: none;
  border: none;
  color: #1e40af;
  font-size: 1.25rem;
  line-height: 1;
  cursor: pointer;
  padding: 0;
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  transition: background-color 0.2s;
}

.remove-btn:hover {
  background: #dbeafe;
}

.upgrade-prompt {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 2rem;
  border-radius: 8px;
  text-align: center;
  margin-bottom: 2rem;
}

.upgrade-content h3 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
}

.upgrade-content p {
  font-size: 1rem;
  margin-bottom: 1.5rem;
  opacity: 0.9;
}

.upgrade-btn {
  display: inline-block;
  padding: 0.75rem 2rem;
  background: white;
  color: #667eea;
  border-radius: 6px;
  font-weight: 600;
  text-decoration: none;
  transition: transform 0.2s;
}

.upgrade-btn:hover {
  transform: translateY(-2px);
}

.loading-state {
  text-align: center;
  padding: 3rem;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #e5e7eb;
  border-top-color: #2563eb;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 1rem;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.error-state {
  text-align: center;
  padding: 2rem;
  background: #fee2e2;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.error-message {
  color: #991b1b;
  margin-bottom: 1rem;
}

.retry-btn {
  padding: 0.5rem 1.5rem;
  background: #dc2626;
  color: white;
  border: none;
  border-radius: 6px;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.retry-btn:hover {
  background: #b91c1c;
}

.comparison-section {
  background: white;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.comparison-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.comparison-header h2 {
  font-size: 1.5rem;
  font-weight: 600;
  color: #111827;
}

.export-btn {
  padding: 0.5rem 1.5rem;
  background: #10b981;
  color: white;
  border: none;
  border-radius: 6px;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.export-btn:hover:not(:disabled) {
  background: #059669;
}

.export-btn:disabled {
  background: #9ca3af;
  cursor: not-allowed;
}

.action-remove-btn {
  padding: 0.25rem 0.75rem;
  background: #ef4444;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.action-remove-btn:hover {
  background: #dc2626;
}

.empty-state {
  text-align: center;
  padding: 4rem 2rem;
  background: white;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.empty-icon {
  width: 64px;
  height: 64px;
  color: #9ca3af;
  margin: 0 auto 1rem;
}

.empty-state h3 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #374151;
  margin-bottom: 0.5rem;
}

.empty-state p {
  font-size: 1rem;
  color: #6b7280;
}

/* Mobile responsive */
@media (max-width: 768px) {
  .compare-page {
    padding: 1rem 0.5rem;
  }

  .page-title {
    font-size: 1.5rem;
  }

  .comparison-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }

  .export-btn {
    width: 100%;
  }
}
</style>

// frontend/app/[locale]/compare/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useAuthStore } from '@/stores/auth';
import { useBatchComparison } from '@/hooks/useStockData';
import StockTable from '@/components/StockTable';
import StockSearchBar from '@/components/StockSearchBar';
import { useRouter } from 'next/navigation';
import { PlusIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

/**
 * Comparison page for batch stock comparison
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5
 */
export default function ComparePage() {
  const router = useRouter();
  const { isAuthenticated, isPro } = useAuthStore();
  const [selectedTickers, setSelectedTickers] = useState<string[]>([]);
  const [showSearch, setShowSearch] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Fetch comparison data
  const { data: comparisonData, isLoading, error } = useBatchComparison(selectedTickers);

  // Check authentication
  useEffect(() => {
    if (mounted && !isAuthenticated) {
      toast.error('Please login to use comparison feature');
      router.push('/login');
    }
  }, [mounted, isAuthenticated, router]);

  // Add stock to comparison
  const handleAddStock = (ticker: string) => {
    // Check if user is Pro for more than 1 stock (Requirement 4.4)
    if (!isPro && selectedTickers.length >= 1) {
      toast.error('Upgrade to Pro to compare multiple stocks');
      setShowSearch(false);
      return;
    }

    // Check limit of 50 stocks for Pro users (Requirement 4.2)
    if (selectedTickers.length >= 50) {
      toast.error('Maximum 50 stocks allowed for comparison');
      setShowSearch(false);
      return;
    }

    // Check if already added
    if (selectedTickers.includes(ticker)) {
      toast.error('Stock already added to comparison');
      setShowSearch(false);
      return;
    }

    setSelectedTickers([...selectedTickers, ticker]);
    setShowSearch(false);
    toast.success(`${ticker} added to comparison`);
  };

  // Remove stock from comparison
  const handleRemoveStock = (ticker: string) => {
    setSelectedTickers(selectedTickers.filter((t) => t !== ticker));
    toast.success(`${ticker} removed from comparison`);
  };

  // Handle export (Pro only)
  const handleExport = async (format: 'csv' | 'pdf') => {
    if (!isPro) {
      toast.error('Upgrade to Pro to export data');
      return;
    }

    try {
      const API_BASE_URL = process.env['NEXT_PUBLIC_API_BASE_URL'] || 'http://localhost:3001';
      const tickers = selectedTickers.join(',');
      const url = `${API_BASE_URL}/api/download?format=${format}&tickers=${tickers}`;
      
      // Open in new window to trigger download
      window.open(url, '_blank');
      toast.success(`Exporting as ${format.toUpperCase()}...`);
    } catch (error) {
      toast.error('Export failed. Please try again.');
    }
  };

  if (!mounted) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 py-4 sm:py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header - Requirements: 12.1, 12.2 */}
        <div className="mb-6 sm:mb-8">
          <h1 className="text-2xl sm:text-3xl font-bold text-black mb-2">Stock Comparison</h1>
          <p className="text-sm sm:text-base text-gray-600">
            Compare fair values across multiple stocks
            {!isPro && (
              <span className="block sm:inline sm:ml-2 text-xs sm:text-sm text-gray-500 mt-1 sm:mt-0">
                (Free tier: 1 stock only)
              </span>
            )}
          </p>
        </div>

        {/* Upgrade Prompt for Free Users (Requirement 4.4) - Requirements: 12.1, 12.2 */}
        {!isPro && (
          <div className="mb-4 sm:mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex flex-col sm:flex-row sm:items-start gap-3">
              <div className="flex-1">
                <h3 className="text-sm sm:text-base font-semibold text-blue-900 mb-1">
                  Upgrade to Pro for Unlimited Comparisons
                </h3>
                <p className="text-xs sm:text-sm text-blue-700">
                  Compare up to 50 stocks side-by-side and export results
                </p>
              </div>
              <button
                onClick={() => router.push('/pricing')}
                className="w-full sm:w-auto px-4 py-2 min-h-touch bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700 transition-colors whitespace-nowrap"
              >
                Upgrade Now
              </button>
            </div>
          </div>
        )}

        {/* Add Stock Section - Requirements: 12.1, 12.2 */}
        <div className="mb-4 sm:mb-6 bg-white border border-gray-200 rounded-lg p-4 sm:p-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-0 mb-4">
            <h2 className="text-base sm:text-lg font-semibold text-black">
              Selected Stocks ({selectedTickers.length}{isPro ? '/50' : '/1'})
            </h2>
            <button
              onClick={() => setShowSearch(!showSearch)}
              className="inline-flex items-center justify-center px-4 py-2 min-h-touch bg-black text-white text-sm font-medium rounded-md hover:bg-gray-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={(!isPro && selectedTickers.length >= 1) || selectedTickers.length >= 50}
            >
              <PlusIcon className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
              Add Stock
            </button>
          </div>

          {/* Search Bar */}
          {showSearch && (
            <div className="mb-4">
              <StockSearchBar
                onSelect={handleAddStock}
                placeholder="Search for a stock to add..."
              />
            </div>
          )}

          {/* Selected Tickers */}
          {selectedTickers.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {selectedTickers.map((ticker) => (
                <div
                  key={ticker}
                  className="inline-flex items-center px-3 py-1 bg-gray-100 text-gray-800 rounded-full text-sm"
                >
                  <span className="font-medium">{ticker}</span>
                  <button
                    onClick={() => handleRemoveStock(ticker)}
                    className="ml-2 text-gray-500 hover:text-red-600 transition-colors"
                    aria-label={`Remove ${ticker}`}
                  >
                    ×
                  </button>
                </div>
              ))}
            </div>
          )}

          {selectedTickers.length === 0 && (
            <p className="text-gray-500 text-sm">
              No stocks selected. Click "Add Stock" to get started.
            </p>
          )}
        </div>

        {/* Export Buttons (Pro only) - Requirements: 12.1, 12.2 */}
        {selectedTickers.length > 0 && isPro && (
          <div className="mb-4 sm:mb-6 flex flex-col sm:flex-row gap-3">
            <button
              onClick={() => handleExport('csv')}
              className="inline-flex items-center justify-center px-4 py-2 min-h-touch bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-md hover:bg-gray-50 transition-colors"
            >
              <ArrowDownTrayIcon className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
              Export CSV
            </button>
            <button
              onClick={() => handleExport('pdf')}
              className="inline-flex items-center justify-center px-4 py-2 min-h-touch bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-md hover:bg-gray-50 transition-colors"
            >
              <ArrowDownTrayIcon className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
              Export PDF
            </button>
          </div>
        )}

        {/* Comparison Table */}
        {isLoading && selectedTickers.length > 0 && (
          <div className="bg-white border border-gray-200 rounded-lg p-12 text-center">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-black"></div>
            <p className="mt-4 text-gray-600">Loading comparison data...</p>
          </div>
        )}

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-center">
            <p className="text-red-700">
              Failed to load comparison data. Please try again.
            </p>
          </div>
        )}

        {comparisonData && comparisonData.length > 0 && (
          <StockTable
            data={comparisonData}
            onRemove={handleRemoveStock}
            showRemoveButton={true}
          />
        )}

        {selectedTickers.length === 0 && !isLoading && (
          <div className="bg-white border border-gray-200 rounded-lg p-12 text-center">
            <p className="text-gray-500 mb-4">
              Add stocks to start comparing their fair values
            </p>
            <button
              onClick={() => setShowSearch(true)}
              className="inline-flex items-center px-6 py-3 bg-black text-white font-medium rounded-md hover:bg-gray-800 transition-colors"
            >
              <PlusIcon className="w-5 h-5 mr-2" />
              Add Your First Stock
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
